Prac0/VideoStore.WebClient/ViewModels/ReviewViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using VideoStore.Services.MessageTypes;

namespace VideoStore.WebClient.ViewModels
{
    public class ReviewViewModel
    {
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required] 
        [DataType(DataType.Text)]
        [Display(Name = "Rating")]
        [Range(0,5)]
        public int Rating { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Review Text")]
        public string ReviewText { get; set; } 
    }
}

Prac0/VideoStore.WebClient/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using VideoStore.Services.MessageTypes;
using VideoStore.WebClient.ViewModels;

namespace VideoStore.WebClient.Controllers
{
    public class ReviewController : Controller
    {
        public ActionResult Index(int mediaId)
        {
            var mediaDetialsViewModel = new MediaDetailsViewModel
            {
                Media = ServiceFactory.Instance.CatalogueService.GetMediaById(mediaId),
                Reviews = ServiceFactory.Instance.ReviewService.GetReviewItems(mediaId, 0, int.MaxValue)
            };

            return View(mediaDetialsViewModel);
        }

        public ActionResult CreateReview(int mediaId)
        {
            ViewBag.MediaId = mediaId;

            return View();
        }

        [HttpPost]
        public ActionResult CreateReview(int mediaId, ReviewViewModel pReview, UserCache pUser)
        {
            var author = new ReviewAuthor
            {
                Id = pUser.Model.Id,
                Name = pUser.Model.Name,
                City = pUser.Model.City,
                Country = pUser.Model.Country
            };

            var review = new Review
            {
                Title = pReview.Title,
                Date = DateTime.Now,
                Rating = pReview.Rating,
                ReviewText = pReview.ReviewText, 
            };

            ServiceFactory.Instance.ReviewService.CreateReview(mediaId, review, author);

            return RedirectToAction("Index", new { mediaId });
        }
    }
}

Prac0/VideoStore.WebClient/Views/Review/CreateReview.cshtml
@model VideoStore.WebClient.ViewModels.ReviewViewModel
@{
    ViewBag.Title = "Write a review";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Write a review</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">

            @using (Html.BeginForm("CreateReview", "Review", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.Hidden("mediaId", (int)ViewBag.MediaId)
                
                <div class="form-group">
                    @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Rating, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Rating, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Rating, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ReviewText, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.ReviewText, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ReviewText, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>
            }


        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prac0/VideoStore.WebClient/Views/Review/Index.cshtml
@model   VideoStore.WebClient.ViewModels.MediaDetailsViewModel
@{
    ViewBag.Title = "Media Reviews";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Media Details</h2>
<p>Title: @Model.Media.Title </p>
<p>
    Price: $@Model.Media.Price
</p>
<p> Quantity: @Model.Media.StockCount</p>
<p> Average Rating: @decimal.Round(Model.Media.AverageRating,2)</p>
<p> Ratings Count: @Model.Media.RatingsCount</p>
 
@Html.ActionLink("Write a review", "CreateReview", new { mediaId = Model.Media.Id })

<ul>
    @foreach (var item in Model.Reviews)
    {
        <li> Rating:<b>@item.Rating</b>  | Title: @item.Title | Review text: @item.ReviewText on @item.Date </li>
    }
    
</ul>